eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9099
spring:
  application:
    name: accountservice
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true